
MIN_HASH = 0L
MAX_HASH = pow(2, 160) - 1

DS_INITIALIZE = 'init'
DS_NORMALWORK = 'normwork'

WAIT_RANGE_TIMEOUT = 120
DHT_CYCLE_TRY_COUNT = 3

ALLOW_FREE_SIZE_PERCENTS = 70
MAX_FREE_SIZE_PERCENTS = 90

#init dht thread constants
INIT_DHT_WAIT_NEIGHBOUR_TIMEOUT = 1
WAIT_RANGES_TIMEOUT = 10

MONITOR_DHT_RANGES_TIMEOUT = 120
RESERV_RANGE_FILE_MD_TIMEDELTA = 120
